### ISSUE TITLE
How to install WMRilShim?

### ISSUE THREAD

**Issue by quiret** [WOA-Project/WMRilShim#1]
Dear gus33000,

I want to collect cellular API data to help you in your RILServiceInit efforts. Could you please tell us how to install this shim layer? I have changed ntddrilapitypes.h into rilapitypes.h and it compiled just fine. BUT now what?

EDIT: figured out that rilapitypes.h comes with the latest WDK 10.0.18362.0 and that it is located in um/rilapitypes.h

- Martin

**Comment by gus33000** [comment]
Place the shim in system32 and redirect RILAdaptation to use that ril instead of WMRil.

**Comment by quiret** [comment]
Thank you for the tip, gus! I got it working by modifying the Windows Registry at:
- Computer\HKEY_LOCAL_MACHINE\ControlSet001\Services\RILAdaptation\Parameters\0000
- Property Name: RILPath

Kind of sweet, creates this logfile in the drive root.
